server:
  port: 3344 #测试 http://localhost:3344/application-dev.yml

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lzgblog/springcloud-application-config.git #GitHub上面的git仓库名字